# Pipeline Status is not in the model to allow usage in different
PIPELINE_STATUS_FAIL = 'failed'
PIPELINE_STATUS_SUCCESS = 'success'
PIPELINE_STATUS_INPROGRESS = 'in progress'

PIPELINE_STATUS_CHOICES = (
    (PIPELINE_STATUS_FAIL, PIPELINE_STATUS_FAIL),
    (PIPELINE_STATUS_SUCCESS, PIPELINE_STATUS_SUCCESS),
    (PIPELINE_STATUS_INPROGRESS, PIPELINE_STATUS_INPROGRESS),
)
