# Generated by Django 2.2.7 on 2020-01-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unit", "0001_alwaysupdate_onlyoncreate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimpleModel",
            fields=[("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),],
        ),
    ]
