# Generated by Django 2.1.5 on 2019-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katka', '0014_update_pipeline_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scmpipelinerun',
            name='status',
            field=models.CharField(choices=[('initializing', 'initializing'), ('in progress', 'in progress'), ('failed', 'failed'), ('success', 'success')], default='initializing', max_length=30),
        ),
    ]
