# Generated by Django 2.2.7 on 2020-04-03 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("katka", "0033_scmpipelinerun_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="sys_users",
            field=models.ManyToManyField(related_name="sys_teams", to=settings.AUTH_USER_MODEL),
        ),
    ]
